Repository ucsb-cs156-s24/proj-happycows-s24-4pm-6, pull requests merged in 2024-06, with the labels that each got.

#43 Dakota - H2 Console NavBar link Visibility Environment Variable
  src/main/resources/application-development.properties
Labels: Ready for Staff Review

#50 Fixed Post Announcement Endpoint
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcement.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 10

#63 PR: FIX: BUG [nonexistent commons returns blank page / commons chat should not be available to users who are not part of a commons]
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: Ready for Staff Review

#57 Announcements edit button (1/2)
  frontend/src/App.js
  frontend/src/main/components/Announcement/AnnouncementTable.js
  frontend/src/main/pages/AdminCreateAnnouncementsPage.js
  frontend/src/main/pages/AdminEditAnnouncementPage.js
  frontend/src/tests/components/Announcement/AnnouncementsTable.test.js
  frontend/src/tests/pages/AdminCreateAnnouncementsPage.test.js
  frontend/src/tests/pages/AdminEditAnnouncementPage.test.js
Labels: Ready for Staff Review

#61 Announcements Delete Button (2/2)
  frontend/src/main/components/Announcement/AnnouncementTable.js
  frontend/src/main/pages/AdminCreateAnnouncementsPage.js
  frontend/src/tests/components/Announcement/AnnouncementsTable.test.js
  frontend/src/tests/pages/AdminListAnnouncementsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: Ready for Staff Review, 10
