Repository ucsb-cs156-s24/proj-happycows-s24-4pm-6, pull requests merged in 2024-05, with the labels that each got.

#19 PR: FIX for [ Issue#2 | BUG: Change default start date when creating a commons to be today's date ]
  frontend/src/main/components/Commons/CommonsForm.js
Labels: FIXME-Peer CR

#37 B1: Add suspended field to users entity
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
Labels: Ready for Staff Review

#25 PR: [BUG] Fix CommonsController delete that does not allow deleting user with associated profit table
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java
Labels: 10

#30 PR: FIX: [BUG: Disallow ability to navigate to unjoined commons]
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: Ready for Staff Review

#33 PR: FIX: [BUG: Starting date fix still has issue with month and year.]
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/utils/dateUtils.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/utils/dateUtils.test.js
Labels: 10

#42 Dakota - Swagger NavBar link Visibility Environment Variable for dokku
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: Ready for Staff Review

#49 Pc fix pitest broken suddenly on main
  README.md
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelper.java
  src/main/java/edu/ucsb/cs156/happiercows/helpers/ReportCSVHelper.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelperTests.java
  src/test/java/edu/ucsb/cs156/happiercows/helpers/ReportCSVHelperTests.java
Labels: Ready for Staff Review

#35 Admin Can Read Announcements
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminListAnnouncementsPage.js
  frontend/src/main/utils/currentUser.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminListAnnouncementsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: Ready for Staff Review

#47 Issues B3a & B3b: Add code that monitors role changes and gatekeepers suspended users at login time
  src/main/java/edu/ucsb/cs156/happiercows/interceptors/RoleInterceptor.java
  src/main/java/edu/ucsb/cs156/happiercows/interceptors/RoleInterceptorConfig.java
  src/test/java/edu/ucsb/cs156/happiercows/interceptors/RoleInterceptorTests.java
Labels: Ready for Staff Review

#54 PR: FIX [BUG: Remove toast spam on the "Whoa partner" page (Play page navigated to by user not member of commons)]
  frontend/src/main/pages/PlayPage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/utils/useBackend.test.js
Labels: 10
